name: LoginPlusIdentity
version: 1.0.0
main: kazet.loginplus.LoginPlus
api-version: '1.20'
author: Kazet
description: Login / Register / Create Character GUI + KTP (ID card)
commands:
  loginplus:
    description: Command admin LoginPlusIdentity
    usage: /loginplus <reload|unregister|resetpass|givecard>
    permission: loginplus.admin
permissions:
  loginplus.admin:
    description: Akses command admin LoginPlusIdentity
    default: op
